{% set version = '0.20.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mosaicdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mosaicData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mosaicData/mosaicData_{{ version }}.tar.gz
  sha256: 51f66a917a97722859a7fa04ca047caed9478eda5282b99fd8177275f4e6b916

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('mosaicData')"           # [not win]
    - "\"%R%\" -e \"library('mosaicData')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mosaicData
  license: GPL-2.0-or-later
  summary: Data sets from Project MOSAIC (<http://mosaic-web.org>) used to teach mathematics,
    statistics, computation and modeling.  Funded by the NSF, Project MOSAIC is a community
    of educators working to tie together aspects of quantitative work that students
    in science, technology, engineering and mathematics will need in their professional
    lives, but which are usually taught in isolation, if at all.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: mosaicData
# Type: Package
# Title: Project MOSAIC Data Sets
# Version: 0.17.0
# Date: 2018-06-23
# Depends: R (>= 3.0.0)
# Suggests: lattice, mosaic, reshape2, ggplot2, dplyr, tidyr, ggformula
# Author: Randall Pruim <rpruim@calvin.edu>, Daniel Kaplan <kaplan@macalester.edu>, Nicholas Horton <nhorton@amherst.edu>
# Maintainer: Randall Pruim <rpruim@calvin.edu>
# Description: Data sets from Project MOSAIC (<http://mosaic-web.org>) used to teach mathematics, statistics, computation and modeling.  Funded by the NSF, Project MOSAIC is a community of educators working to tie together aspects of quantitative work that students in science, technology, engineering and mathematics will need in their professional lives, but which are usually taught in isolation, if at all.
# License: GPL (>= 2)
# LazyLoad: yes
# LazyData: yes
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-06-23 18:17:54 UTC; rpruim
# Repository: CRAN
# Date/Publication: 2018-06-23 18:37:55 UTC
